services:
  - type: web
    name: fatemiyeh-school
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --listen=0.0.0.0:$PORT app:app
    healthCheckPath: /
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
